name: Terraform-Infr

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - infra/dev
      - feature/infra
      - infra/feature/automation

jobs:
  apply-infra:
    name: Apply infrastructure
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.3  # Cambié de 1.11.3 a 1.1.3 (la 1.11 no existe aún)

      # 3. Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 4. Init Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: Terraform

      # 5. Validate
      - name: Terraform Validate
        run: terraform validate
        working-directory: Terraform

      # 6. Terraform Plan
      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"
        working-directory: Terraform

      # 7. Terraform Apply (solo en master)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/master'
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
        working-directory: Terraform
